@baseUrl = http://localhost:3001/v1

@contentType = application/json

@tokenMaster = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoyMCwic2VjdG9yIjoxLCJpYXQiOjE2MDMzOTI0ODMsImV4cCI6MTYwMzM5OTY4M30.oFEuv2cOZBIn7W-MoDTmkSUth1sTe9gXKwAtlTv86pM

@tokenCoord = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoyMiwic2VjdG9yIjoyLCJpYXQiOjE2MDM0MDA5MjAsImV4cCI6MTYwMzQwODEyMH0.sAQKDTuCuQfVEL3jaXZN_BqrGdvj3zFPR9P5GS_9MyM
@tokenTehc = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoyMCwic2VjdG9yIjoxLCJpYXQiOjE2MDMzOTI0ODMsImV4cCI6MTYwMzM5OTY4M30.oFEuv2cOZBIn7W-MoDTmkSUth1sTe9gXKwAtlTv86pM

@resetToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InlhbmFsbWVpZGFnYXJjaWFAZ21haWwuY29tIiwiY3BmIjoiMDAwLjAyMC4wMDAtMTMiLCJpYXQiOjE2MDMwODQ2MTAsImV4cCI6MTYwMzA4NTUxMH0.BPQc-S6cHd5BH5fRqmScee77tdOa5n72KBPyWxg1E_I


### /auth/sign-in login user - coord (1)

POST {{baseUrl}}/auth/sign-in
Content-Type: {{contentType}}

{
  "login": "yan.andrade",
  "pass": "jhderpsa" 
}


### /auth/sign-in login user - coord (2)

POST {{baseUrl}}/auth/sign-in
Content-Type: {{contentType}}

{
  "login": "yan.garcia-803",
  "pass": "ry2tyqsq" 
}




### /auth/forgot-password

POST {{baseUrl}}/auth/forgot-password
Content-Type: {{contentType}}

{
  "email": "yanalmeidagarcia@gmail.com",
  "cpf": "000.020.000-13"
}


### /auth/reset-password

POST {{baseUrl}}/auth/reset-password
Content-Type: {{contentType}}

{
  "resetToken": "{{resetToken}}",
  "cpf": "000.020.000-13"
}




### /users all users
GET {{baseUrl}}/users
Content-Type: {{contentType}}
Authorization: Bearer {{tokenCoord}}


### /users unique user
GET {{baseUrl}}/users/1
Content-Type: {{contentType}}
Authorization: Bearer {{tokenCoord}}


### /users add user
POST {{baseUrl}}/users
Content-Type: {{contentType}}
Authorization: Bearer {{tokenCoord}}

{
  "cpf": "",
  "email": "yanalmeidagarciagmail",
  "name": "12314",
  "phone": "(61) 14444-4",
  "sector": "a",
  "gender": "b"
}


### /users delete user

PUT {{baseUrl}}/users/223
Content-Type: {{contentType}}
Authorization: Bearer {{tokenCoord}}

{
  "email": "yanalmeidagarcia@gmail.com",
  "phone": "(61) 14444-4444",
  "sector": 2,
  "gender": 2
}


### /users delete user

DELETE {{baseUrl}}/users
Content-Type: {{contentType}}
Authorization: Bearer {{tokenCoord}}

{
  "id_user": 15
}

